uploads = []
outputs = []

[[generated]]
id = "vn8QhqnjoMNA84WuCzPkF"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "intensive finance app icon clean"

[[generated]]
id = "BE0sAl3qCL_zDIk_wGnJz"
uri = "file://artifacts/mobile/assets/images/splash-icon.png"
type = "image"
title = "intensive splash icon white"

[[generated]]
id = "jhsqlmmGPXcvuuIEvOIcf"
uri = "file://artifacts/mobile/assets/images/adaptive-icon.png"
type = "image"
title = "intensive adaptive icon foreground"
